language: node_js
node_js:
  - 8.5.0
before_install:
 - chmod 755 ./deploy.sh
script: npm run build
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_PULL_REQUEST != true"